function rez=EF_PCACluster(mat1, mat2, mat3, nrp)

mat=[mat1; mat2; mat3];
mat=mat/max(abs(mat(:)));
% [pc, zscores, pcvars] = princomp(mat);
zscores=mat;
nrpca=size(mat,2);
n=1;
tg=zeros(size(mat1,1)+size(mat2,1)+size(mat3,1),3);
tg(1:size(mat1,1),1)=1;
tg((size(mat1,1)+1):(size(mat1,1)+size(mat2,1)),2)=1;
tg((size(mat1,1)+size(mat2,1)+1):end,3)=1;
tg=tg';
net = patternnet(nrp);
net.trainParam.epochs = 200;
net.trainParam.goal = 0.000000001;
net.trainParam.max_fail = 200;
[net tr]= train(net,zscores(:,1:nrpca)',tg);
rez=tr.perf(end);